In [11]:
# Write a python code for addition, subtraction and multiplication of two 4x4 matrices.
import numpy as np
A=np.array([[1,2,3,4],[5,6,7,8],[3,2,1,5],[2,3,3,4]])
B=np.array([[3,24,7,5],[3,7,4,1],[4,6,7,9],[9,9,1,1]])
print("sum is : ")
print(A+B)
print("\n")
print("difference is : ")
print(A-B)
print("\n")
print("product is : ")
print(A.dot(B))

sum is : 
[[ 4 26 10  9]
 [ 8 13 11  9]
 [ 7  8  8 14]
 [11 12  4  5]]


difference is : 
[[ -2 -22  -4  -1]
 [  2  -1   3   7]
 [ -1  -4  -6  -4]
 [ -7  -6   2   3]]


product is : 
[[ 57  92  40  38]
 [133 276 116 102]
 [ 64 137  41  31]
 [ 63 123  51  44]]


In [4]:
# Create a 5 by 2 integer array from a range between 100 to
# 200 such that the difference between each element is 10.
# Print the same.
import numpy as np
arr=np.arange(100,200,10).reshape(5,2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [22]:
# Consider two matrices
# M1=([[2,3,4], [6,5,2], [6,7,3]])
# M2=([[1,4,2], [4,3,6],[5,9,8]])
# Calculate manually as well as develop the python program
# for the following:
# (1) matrix multiplication (dot product) 
# (2) inner product
# (3) cross product
# (4) outer product

M1=np.array([[2,3,4], [6,5,2], [6,7,3]])
M2=np.array([[1,4,2], [4,3,6], [5,9,8]])

print("Dot product is : ")
print(M1.dot(M2))
print("\n")

print("Inner product is : ")
print(np.inner(M1,M2))
print("\n")

print("Cross product is : ")
print(np.cross(M1,M2))
print("\n")

print("Outer product is : ")
print(np.outer(M1,M2))


Dot product is : 
[[34 53 54]
 [36 57 58]
 [49 72 78]]


Inner product is : 
[[ 22  41  69]
 [ 30  51  91]
 [ 40  63 117]]


Cross product is : 
[[-10   0   5]
 [ 24 -28  -2]
 [ 29 -33  19]]


Outer product is : 
[[ 2  8  4  8  6 12 10 18 16]
 [ 3 12  6 12  9 18 15 27 24]
 [ 4 16  8 16 12 24 20 36 32]
 [ 6 24 12 24 18 36 30 54 48]
 [ 5 20 10 20 15 30 25 45 40]
 [ 2  8  4  8  6 12 10 18 16]
 [ 6 24 12 24 18 36 30 54 48]
 [ 7 28 14 28 21 42 35 63 56]
 [ 3 12  6 12  9 18 15 27 24]]


In [30]:
# Randomly generate the marks of the 80 students in the range of 40 to 95.
# Write a NumPy program to compute the 70 percentile for all elements in a given array.
# (Hint: use np.random.randint(start,stop,no_of_items) for list generation)
# (Hint: Use np.percentile)

k=np.random.randint(40,95,80)
print("Array generated is : ")
print(k)
print("\n")
percentile_calculated=np.percentile(k,70)
print("70 percentile for given array {}.".format(percentile_calculated))

Array generated is : 
[55 92 84 70 56 51 43 65 44 47 50 86 54 67 84 51 72 48 70 48 94 87 53 62
 78 94 72 45 91 48 91 74 50 55 54 81 46 85 61 71 70 91 48 59 64 52 53 93
 80 82 40 61 53 43 78 58 68 71 94 80 57 93 61 90 44 69 46 50 77 70 55 92
 50 49 57 41 78 64 94 81]


70 percentile for given array 78.0.


In [38]:
# Create the chessboard like structure black-0, white-1 in minimum(2) no. of lines of code. Use indexing of array.

chess=np.arange(1,65,1)
chess=chess.reshape(8,8)
for j in range (0,8):
    if(j%2==0):
        for i in range (0,8):
            if(chess[j][i]%2!=0):
                chess[j][i]=1
            else:
                chess[j][i]=0    
    else:
        for i in range (0,8):
            if(chess[j][i]%2!=0):
                chess[j][i]=0
            else:
                chess[j][i]=1
print(chess)   


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [46]:
# For the question 6 given below use linear algebra package under numpy.
# Add these statements i.e. for eigenvalues,import numpy as np,from numpy import linalg
# np.linalg.eig(a)
# Write a NumPy program to compute the eigenvalues and
# right eigenvectors of a given square array.
# Arr =( [[1,4,8], [8,9,2],[9,7,8]])

import numpy as np
from numpy import linalg
output=()
Arr =( [[1,4,8], [8,9,2],[9,7,8]])
print("Output of np.linalg.eig() function is : ")
output=np.linalg.eig(Arr)
print(output)
print("\n")
print("Eigen values are : ")
print(output[0])                      #first list is set of eign values second is right eigen vectors
print("\n")
print("Right eigen vectors are : ")
print(output[1])


Output of np.linalg.eig() function is : 
(array([18.61713304, -4.50451282,  3.88737977]), array([[-0.44798294, -0.82768979,  0.36471887],
       [-0.52339057,  0.43844259, -0.77347804],
       [-0.7248266 ,  0.35028233,  0.51837426]]))


Eigen values are : 
[18.61713304 -4.50451282  3.88737977]


Right eigen vectors are : 
[[-0.44798294 -0.82768979  0.36471887]
 [-0.52339057  0.43844259 -0.77347804]
 [-0.7248266   0.35028233  0.51837426]]
